import streamlit as st
import tensorflow as tf
import pandas as pd
import altair as alt
from utils import load_and_prep, get_classes


@st.cache(suppress_st_warning=True)
def predict_species(image, model):
    image = load_and_prep(image)
    image = tf.cast(tf.expand_dims(image, axis=0), tf.int16)
    preds = model.predict(image)
    pred_class = class_names[tf.argmax(preds[0])]
    pred_conf = tf.reduce_max(preds[0])
    top_5_i = sorted((preds.argsort())[0][-5:][::-1])
    values = preds[0][top_5_i] * 100
    labels = []
    for x in range(5):
        labels.append(class_names[top_5_i[x]])
    df = pd.DataFrame({"Top 5 Predictions": labels,
                       "F1 Scores": values,
                       'color': ['#EC5953', '#EC5953', '#EC5953', '#EC5953', '#EC5953']})
    df = df.sort_values('F1 Scores')
    return pred_class, pred_conf, df


class_names = get_classes()

st.set_page_config(page_title="Bird Species Identification",
                   page_icon="🐦")

#### SideBar ####

st.sidebar.title("Bird Species Identification")
st.sidebar.write("""
Bird Species identification is an end-to-end **CNN Image Classification Model** which identifies the bird species in your image.\n
Bird identification in Malaysia \n
LIST OF AVAILABLE BIRD TO BE IDENTIFIED
AFRICAN CROWNED CRANE | AFRICAN FIREFINCH | ALBATROSS
ALEXANDRINE PARAKEET | AMERICAN AVOCET | AMERICAN BITTERN
AMERICAN COOT | AMERICAN GOLDFINCH | AMERICAN KESTREL
AMERICAN PIPIT | AMERICAN REDSTART | ANHINGA
ANNAS HUMMINGBIRD | ANTBIRD | ARARIPE MANAKIN
ASIAN CRESTED IBIS | BALD EAGLE | BALI STARLING
BALTIMORE ORIOLE | BANANAQUIT | BANDED BROADBILL
BAR-TAILED GODWIT | BARN OWL | BARN SWALLOW
BARRED PUFFBIRD | BAY-BREASTED WARBLER
BEARDED BARBET | BEARDED REEDLING
BELTED KINGFISHER | BIRD OF PARADISE
BLACK & YELLOW bROADBILL | BLACK FRANCOLIN
BLACK SKIMMER | BLACK SWAN
BLACK TAIL CRAKE | BLACK THROATED BUSHTIT
BLACK THROATED WARBLER | BLACK VULTURE
BLACK-CAPPED CHICKADEE | BLACK-NECKED GREBE
BLACK-THROATED SPARROW | BLACKBURNIAM WARBLER
BLUE GROUSE | BLUE HERON | BOBOLINK
BORNEAN BRISTLEHEAD | BORNEAN LEAFBIRD
BROWN NOODY | BROWN THRASHER
BULWERS PHEASANT | CACTUS WREN
CALIFORNIA CONDOR | CALIFORNIA GULL
CALIFORNIA QUAIL | CANARY
CAPE MAY WARBLER | CAPUCHINBIRD
CARMINE BEE-EATER | CASPIAN TERN
CASSOWARY | CEDAR WAXWING
CHARA DE COLLAR | CHIPPING SPARROW
CHUKAR PARTRIDGE | CINNAMON TEAL
CLARKS NUTCRACKER | COCK OF THE  ROCK
COCKATOO | COMMON FIRECREST
COMMON GRACKLE | COMMON HOUSE MARTIN
COMMON LOON | COMMON POORWILL
COMMON STARLING | COUCHS KINGBIRD
CRESTED AUKLET | CRESTED CARACARA
CRESTED NUTHATCH | CROW | CROWNED PIGEON
CUBAN TODY | CURL CRESTED ARACURI
D-ARNAUDS BARBET | DARK EYED JUNCO
DOUBLE BARRED FINCH | DOWNY WOODPECKER
EASTERN BLUEBIRD | EASTERN MEADOWLARK
EASTERN ROSELLA | EASTERN TOWEE
ELEGANT TROGON | ELLIOTS  PHEASANT
EMPEROR PENGUIN | EMU
ENGGANO MYNA | EURASIAN GOLDEN ORIOLE
EURASIAN MAGPIE | EVENING GROSBEAK
FIRE TAILLED MYZORNIS | FLAME TANAGER
FLAMINGO | FRIGATE | GAMBELS QUAIL
GANG GANG COCKATOO | GILA WOODPECKER
GILDED FLICKER | GLOSSY IBIS
GO AWAY BIRD | GOLD WING WARBLER
GOLDEN CHEEKED WARBLER | GOLDEN CHLOROPHONIA
GOLDEN EAGLE | GOLDEN PHEASANT
GOLDEN PIPIT | GOULDIAN FINCH
GRAY CATBIRD | GRAY PARTRIDGE
GREAT POTOO | GREATOR SAGE GROUSE
GREEN JAY | GREEN MAGPIE
GREY PLOVER | GUINEA TURACO
GUINEAFOWL | GYRFALCON
HARPY EAGLE | HAWAIIAN GOOSE
HELMET VANGA | HIMALAYAN MONAL | HOATZIN
HOODED MERGANSER | HOOPOES
HORNBILL | HORNED GUAN | HORNED SUNGEM
HOUSE FINCH | HOUSE SPARROW
IMPERIAL SHAQ | INCA TERN
INDIAN BUSTARD | INDIAN PITTA
INDIGO BUNTING | JABIRU
JAVA SPARROW | KAKAPO
KILLDEAR | KING VULTURE | KIWI | KOOKABURRA
LARK BUNTING | LEARS MACAW | LILAC ROLLER
LONG-EARED OWL | MAGPIE GOOSE
MALABAR HORNBILL | MALACHITE KINGFISHER
MALEO | MALLARD DUCK | MANDRIN DUCK
MARABOU STORK | MASKED BOOBY | MASKED LAPWING
MIKADO  PHEASANT | MOURNING DOVE | MYNA
NICOBAR PIGEON | NOISY FRIARBIRD
NORTHERN BALD IBIS | NORTHERN CARDINAL
NORTHERN FLICKER | NORTHERN GANNET
NORTHERN GOSHAWK | NORTHERN JACANA
NORTHERN MOCKINGBIRD | NORTHERN PARULA
NORTHERN RED BISHOP | NORTHERN SHOVELER
OCELLATED TURKEY | OKINAWA RAIL
OSPREY | OSTRICH | OVENBIRD | OYSTER CATCHER
PAINTED BUNTIG | PALILA | PARADISE TANAGER
PARAKETT  AKULET | PARUS MAJOR | PEACOCK
PELICAN | PEREGRINE FALCON | PHILIPPINE EAGLE
PINK ROBIN | PUFFIN | PURPLE FINCH
PURPLE GALLINULE | PURPLE MARTIN
PURPLE SWAMPHEN | PYGMY KINGFISHER
QUETZAL | RAINBOW LORIKEET | RAZORBILL
RED BEARDED BEE EATER | RED BELLIED PITTA
RED BROWED FINCH | RED FACED CORMORANT
RED FACED WARBLER | RED HEADED DUCK
RED HEADED WOODPECKER | RED HONEY CREEPER
RED TAILED THRUSH | RED WINGED BLACKBIRD
RED WISKERED BULBUL | REGENT BOWERBIRD
RING-NECKED PHEASANT | ROADRUNNER
ROBIN | ROCK DOVE | ROSY FACED LOVEBIRD
ROUGH LEG BUZZARD | ROYAL FLYCATCHER
RUBY THROATED HUMMINGBIRD | RUFOUS KINGFISHER
RUFUOS MOTMOT | SAMATRAN THRUSH
SAND MARTIN | SCARLET IBIS
SCARLET MACAW | SHOEBILL | SHORT BILLED DOWITCHER
SMITHS LONGSPUR | SNOWY EGRET
SNOWY OWL | SORA | SPANGLED COTINGA
SPLENDID WREN | SPOON BILED SANDPIPER
SPOONBILL | SRI LANKA BLUE MAGPIE
STEAMER DUCK | STORK BILLED KINGFISHER
STRAWBERRY FINCH | STRIPPED SWALLOW
SUPERB STARLING | SWINHOES PHEASANT
TAIWAN MAGPIE | TAKAHE | TASMANIAN HEN
TEAL DUCK | TIT MOUSE
TOUCHAN | TOWNSENDS WARBLER
TREE SWALLOW | TRUMPTER SWAN
TURKEY VULTURE | TURQUOISE MOTMOT
UMBRELLA BIRD | VARIED THRUSH
VENEZUELIAN TROUPIAL | VERMILION FLYCATHER
VICTORIA CROWNED PIGEON | VIOLET GREEN SWALLOW
VULTURINE GUINEAFOWL | WATTLED CURASSOW
WHIMBREL | WHITE CHEEKED TURACO
WHITE NECKED RAVEN | WHITE TAILED TROPIC
WHITE THROATED BEE EATER | WILD TURKEY
WILSONS BIRD OF PARADISE | WOOD DUCK
YELLOW BELLIED FLOWERPECKER | YELLOW CACIQUE
YELLOW HEADED BLACKBIRD
""")
st.sidebar.write("""
**Dataset :** [**Bird Species**](https://www.kaggle.com/gpiosenka/100-bird-species)
""")
st.sidebar.write("""
**Model :** **`EfficientNetB1`**\n
**Accuracy :** **`93.69%`**\n

**Model :** **`ResNet50`**\n
**Accuracy :** **`90.98%`**\n
""")

st.sidebar.markdown("""
created by group 2 CS2303B2"\n
 afif,anis,afaf,alif 

""")


#### Main Body ####


st.title("Bird Species 🦜🔍")
st.header("Identify your bird species!")
st.write(
    "MADE WITH LOVE")

model = tf.keras.models.load_model("EfficientNetModel.hdf5")

file = st.file_uploader(label="Upload an image of bird.",
                        type=["jpg", "jpeg", "png"])

if not file:
    st.warning("Please upload an image")
    st.stop()

else:
    image = file.read()
    st.image(image, use_column_width=True)
    pred_button = st.button("Predict")

if pred_button:
    pred_class, pred_conf, df = predict_species(image, model)
    st.success(
        f"""Prediction : {pred_class} | Confidence : {pred_conf*100:.2f}%""")
    st.write(alt.Chart(df).mark_bar().encode(
        x='F1 Scores',
        y=alt.X('Top 5 Predictions', sort=None),
        color=alt.Color("color", scale=None),
        text='F1 Scores'
    ).properties(width=800, height=600))
